version: "3"

services:
  elementsd_liquid:
    restart: unless-stopped
    container_name: btcpayserver_elementsd_liquid
    image: btcpayserver/elements:0.21.0.1
    environment:
      ELEMENTS_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      ELEMENTS_MAINNET_CHAIN: "liquidv1"
      ELEMENTS_WALLETDIR: "/walletdata"
      ELEMENTS_EXTRA_ARGS: |
        rpcport=43782
        rpcbind=0.0.0.0:43782
        rpcuser=liquid
        rpcpassword=liquid
        rpcallowip=0.0.0.0/0
        port=39388
        whitelist=0.0.0.0/0
        validatepegin=0
        fallbackfee=0.000001
    expose:
      - "43782"
      - "39388"
    volumes:
      - "elements_datadir:/data"
      - "elements_wallet_datadir:/walletdata"
  nbxplorer:
    environment:
      NBXPLORER_CHAINS: "lbtc"
      NBXPLORER_LBTCRPCURL: http://elementsd_liquid:43782/
      NBXPLORER_LBTCNODEENDPOINT: elementsd_liquid:39388
      NBXPLORER_LBTCRPCUSER: "liquid"
      NBXPLORER_LBTCRPCPASSWORD: "liquid"
    volumes:
      - "elements_datadir:/root/.elements"
  btcpayserver:
    environment:
      BTCPAY_CHAINS: "lbtc"
      BTCPAY_LBTCEXPLORERURL: http://nbxplorer:32838/
volumes:
  elements_datadir:
  elements_wallet_datadir:

recommended:
  - "liquid-default-prune"
